name: sample-worfklow2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: uv sync --frozen

      - name: Run Tests
        run: uv run pytest -v