name: sample-worfklow2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: uv sync --frozen --no-build

      - name: Run Tests
        run: |
          mkdir -p reports
          uv run --frozen --no-build pytest --junitxml=reports/test-results.xml --cov=. --cov-report=xml --cov-report=term-missing -v

      - name: Upload Test Results
        uses: actions/upload-artifact@v5.0.0
        with:
          name: test-results
          path: reports/

  codeql:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write #required to upload codeql results to github
    strategy:
      matrix:
        language: [python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          languages: ${{ matrix.language }}
          category: "security"
          