name: sample-worfklow
on: workflow_dispatch

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in job1
        run: echo "Hello, world!"
      - name: Checking OS Release for Github Runner
        run: cat /etc/os-release
      - name: Calling Sleep
        run: sleep 10

  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - name: Checking name of Runner
        run: hostname
      - name: Runing multiple commands in job2
        run: |
          echo "Hello, world!"
          echo "Current date and time: $(date)"
          sleep 20

  job3:
    name: job3
    needs: [job1, job2]
    runs-on: windows-latest
    steps:
      - name: Dependent Windows job
        shell: pwsh
        run: get-computerinfo